### ISSUE TITLE
Change version release approach

### ISSUE THREAD

**Issue by skmorgane** [weecology/PortalData#189]
We are going to automate the release process as part of a push to change our data archiving (no more Data Papers, but a more living archiving approach). To do this there are a variety of steps that need to be implemented:

- [x] Issue #190: create a new flag in the data tables that says whether data is "good to go" or "under construction" (more technical terms will be needed)
- [x] #192 script that autochanges dataflag to change status of data in datatable when it comes out of the QA/QC period (i.e. for the rodents)
- [x] Issue #191 Change how our process for creating the releases so that all the data is released 
- [x] Issue https://github.com/weecology/portalr/issues/107: Portalr will default to stripping out the malleable data and providing the stable data, but with an option to provide data still under QA/QC
- [x] Issue #191: everytime new data is added, we autorelease a new version
- [x] Issue #178: we will want to have a numbering scheme that provides info that distinguishes between "we added data to existing datasets", "we changed something that will break your code"
- [x] Issue #188: releases will be auto-archived on Zenodo
